### ISSUE TITLE
TNP shows up as civilian in death and chat messages

### ISSUE THREAD

**Issue by gioporta** [LexTheGreat/TLX.Takistan#11]
When killing a TNP officer, they are shown as an armed or unarmed civilian in the death message. In addition, when sending a chat message, they are also shown as a civilian.

**Comment by LexTheGreat** [comment]
TNP are civilian police, although will look into

**Comment by gioporta** [comment]
@LexTheGreat right now TNP is killed constantly by Blufor because the only way to currently identify them is their uniform. This would be one of several things that could help fix that problem (the other being #10)

**Comment by LexTheGreat** [comment]
@GiovanniPorta TNP require [TNP] In name now
