### ISSUE TITLE
Bugs bugs and more bugsss

### ISSUE THREAD

**Issue by MartinKjenna** [LexTheGreat/TLX.Takistan#16]
Yo lex bby, it's martin here.
So here it is:
Can't buy bank insurance in southern civ spawn
I don't know if Civ terrorists are supposed to declare terror anymore, cause if you enter the terror hideout, you get teleported out.

Ya'll didn't add my VIP suggestions, I'm very hurt by this :(

**Comment by strideynet** [comment]
This update purely covered the key mechanics. I will take a look at bank insurance not being avalaible as this should have already been fixed.

Not sure on the terror thing but I will check the code for you and rectify if it is fucked up.

As for the VIP suggestions, if lex is onboard, I will happily take on coding those in.

**Comment by gioporta** [comment]
For reference:

Bank insurance - issue #2 
Civ terrorists getting teleported out - issue #20
