### ISSUE TITLE
Invalid licenses

### ISSUE THREAD

**Issue by Bradys11** [LexTheGreat/TLX.Takistan#17]
So a couple of opfor vehicles require patrol officer license, but as an opfor, you can not obtain one.

**Comment by LexTheGreat** [comment]
fcebd9a3c50a36ac662b008902a17f8dccc0e84a

**Comment by gioporta** [comment]
@LexTheGreat UH-1H Huey at Opfor base still requires SOBR Training to purchase.

**Comment by LexTheGreat** [comment]
Alright then there may be other things that were missed. List is to large to go through.. Anything else that requires licenses that you can't get?

**Comment by LexTheGreat** [comment]
ea6e582d26ff04cd1326c281ef9d570a42c4694d

**Comment by gioporta** [comment]
Went through all the Opfor shops, did not find any other Blufor licensing issues.

However, I did notice that the only helicopter with Soviet Aircraft Training is the Huey (since it was only just changed), should all the helicopters require aircraft training, or should only the jets?

**Comment by LexTheGreat** [comment]
Yeah, all aircrafts should use the training
https://github.com/LexTheGreat/TLX.Takistan/commit/f0555dbe0edb0608849b0e8d237549441adc1693

**Comment by LexTheGreat** [comment]
https://github.com/LexTheGreat/TLX.Takistan/commit/c63fbd41e655ef3b1c344d8abb7bfb72a96999ab

**Comment by gioporta** [comment]
Why is there Soviet Vehicle Training and Soviet Aircraft Training at TNP base available for purchase? There doesn't seem to be anything there that uses them.

**Comment by Bradys11** [comment]
why is yall emailing me?

-Bradys

**Comment by Bradys11** [comment]
Want to hear a great april fools joke?













april fools itself
