### ISSUE TITLE
Getting teleported out of terrorist hideout

### ISSUE THREAD

**Issue by A-JAY99** [LexTheGreat/TLX.Takistan#20]
A-JAY here
Whenever I am entering the terrorist hideout I get teleported out and can't get in whatsoever. I hear a lot of other people having this issue as well. People can't even become terrorists right now so it needs to be fixed. Thanks.

**Comment by strideynet** [comment]
Need to discuss this with lex personally but I believe for now the only terrorists are those is the new terrorist slots. The whole mechanic of declaring terror is just replaced with thise slots. Can anyone confirm that people in terrorist slots can't go there? If so that is an issue.

**Comment by LexTheGreat** [comment]
It's a bug, there is no declaring terror. Going to look into it

**Comment by LexTheGreat** [comment]
8ad6296f596be34712a78a0fcb80b62a8749a454
