### ISSUE TITLE
Some OPFOR and NATO slots are Supporter Only

### ISSUE THREAD

**Issue by ghost** [LexTheGreat/TLX.Takistan#21]
Some of the OPFOR and NATO slots are still Supporter Only like they were before the update.

**Comment by strideynet** [comment]
Oh shit. Looks like a case of simply forgetting. If lex doesn't sort this tonight I will happily do it tomorrow.

**Comment by gioporta** [comment]
[whitelist_blacklist.sqf](https://github.com/LexTheGreat/TLX.Takistan/blob/f360b8bc9389e80a7c331bb72e3126e76ceedc2b/Scripts/whitelist_blacklist.sqf)

`if(!issup) then {
    if((rolenumber == 70) ||(rolenumber >= 73 && rolenumber <= 82)||(rolenumber >= 92 && rolenumber <= 95)) then {
        player groupChat "You cannot join a supporter slot without supporter privileges!";
        sleep 7;
        failMission "END1";
    };
};`

Assuming this is the problematic code?

**Comment by ghost** [comment]
Like to add = Civ59 (PMC) is not a donor only slot anymore

**Comment by LexTheGreat** [comment]
a696a1703f376c7bd3fbcdaecb209c1bb4fc38b5
