### ISSUE TITLE
TNP Lose weapons on death

### ISSUE THREAD

**Issue by strideynet** [LexTheGreat/TLX.Takistan#28]
Tried to fix it but for the life of me can't find the bit of code that does this for blufor!

**Comment by gioporta** [comment]
If this is going to be changed for TNP, can this be done for Opfor too?

**Comment by strideynet** [comment]
It can be, first I want to check that they actually want to retain this feature.

**Comment by LexTheGreat** [comment]
Alright an Idea was brought up to give a small load out to each major faction, weapons wont be saved if died on any faction. You will spawn with a load out (Stun, rifle, ammo, nv, etc) Then you can buy weapons if you want better one for that life
