### ISSUE TITLE
OPFOR Unable to use Radar

### ISSUE THREAD

**Issue by Solvee98** [LexTheGreat/TLX.Takistan#29]
Radar option doesn't exist for any of the slots I've explored. Perhaps add it to the leader slot... Since TLA Commander's been removed? Or share it with Spetsnaz slots?

**Comment by MartinKjenna** [comment]
This also applies to Nato, no radar there anymore either

**Comment by LexTheGreat** [comment]
https://github.com/LexTheGreat/TLX.Takistan/commit/687ca2444ce5258ff220626b026f1c2bc5ebe633

**Comment by Solvee98** [comment]
@LexTheGreat 
Changed by username from Solvee to Comrade incase you're wondering why this is being opened again. But I don't think the fix has worked as I don't see the option to use the radar as OPFOR. Am I missing something or blind? I mostly play TLA Leader.
