### ISSUE TITLE
Terrorists spawn location.

### ISSUE THREAD

**Issue by MartinKjenna** [LexTheGreat/TLX.Takistan#30]
Moving Terrorists spawn location from Feruz Abad to Terrorists hideout. It really is an unnecesary travel, and seeing as they are terrorists by default, they should spawn in the hideout.

**Comment by samwardle1** [comment]
Please do not move my spawn locations or I will bomb you until you cant be bombed no more. Then I will bomb your allies! My people suffer enough with travel, do not make me resort to more interesting situations... Plus, they are normal civilians... They should have to travel just the same... If they spawn in the south they can still buy gear from places like Smuggler :/

**Comment by MartinKjenna** [comment]
But if they were normal civilians, why do we have special slots for them? Makes no sence

**Comment by samwardle1** [comment]
Because then they dont have to declare terror and mess around.
By spawning in Civ Spawn they
A) Can get access to more shops quickly
B) Civilian vehicles
C) Cant instantly go on a mad murder spree
D) Gives them more time to plan out their attacks.

Their should be risk involved in them arming up and moving around the map. Not just spawn in buy gun then bam.

**Comment by MartinKjenna** [comment]
Fair enough. I still think southern takistan is a stupid spawn location for them, considering terrorist hideout is like 8km away and cops do actually check who's in the terror slots and KOS them not caring about wether or not they declared terror.

**Comment by samwardle1** [comment]
They cant declare terror that was removed and they no longer have too. However, I do think that the south spawn could have a gun store moved closer to them then maybe? Just to allow them quicker access to weaponry.

**Comment by LexTheGreat** [comment]
There is a factory for guns right out side of Southern spawn. (North of it) Almost the same distance of North to the gun shop.

**Comment by samwardle1** [comment]
Shhh... I forgot about that..
