### ISSUE TITLE
TNP Suggestions

### ISSUE THREAD

**Issue by Daltonk01** [LexTheGreat/TLX.Takistan#31]
First Suggestion: Fix / Add the speed gun ability to TNP so we can actually police and enforce speeding.

Second Suggestion: Galaxee told me put this, but add the TMP gun to TNP store

Third Suggestion: Add different types of police sirens for TNP and maybe blufor too. Maybe as a scroll wheel option, or just as different letters, since TNP can't use ctrl H, maybe make three sirens using, CTRL F, G, and H.

Fourth Suggestion: Add a supporter npc in the back room of TNP base.

Fifth Suggestion: Relocate the ATM so it is inside the base.

Sixth Suggestion:Add a helicopter NPC so police are able to purchase the little bird and preferably with a skin. I do not know if the heli should spawn on the roof or have a new landing pad for it outside

**Comment by LexTheGreat** [comment]
1. Speed guns have been fixed.
2. TMP Gun?..
3. Un-needed, will make mission size bigger as well...
4. TNP do need a supporter I suppose... Will have to think about this one. As of right now TNP can use civ supporter.
5. I'll think about that one, You don't have to go out side to use it, just get close to it near the wall and press E
6. Soon (/hopefully) it will be on the roof of the TNP stations.

**Comment by Daltonk01** [comment]
I think it'd be really cool though for the sirens, and not that much bigger. Also, yeah the pistol tmp, I don't know Galaxee said it. Also, can you fix the f***ing squad leader telling everyone to disembark and etc. It's so fucking annoying. @LexTheGreat

**Comment by LexTheGreat** [comment]
Turn down your radio sound in the audio settings. Attempts have been made
(His AI Is fully disabled, that is why he doesn't move, act, animated
etc...), although it seems like it's an Arma bug a the moment because his
speech is disable yet talks.

**Comment by Daltonk01** [comment]
When he tells us to disembark it forces us to, and I have always had radio off for ever. @LexTheGreat

**Comment by LexTheGreat** [comment]
Speedgun https://github.com/LexTheGreat/TLX.Takistan/commit/79c4c6d953a42399ca0b6643e9a0a68226cb34f5
