### ISSUE TITLE
Independent Suggestion

### ISSUE THREAD

**Issue by Daltonk01** [LexTheGreat/TLX.Takistan#34]
Hey,

So, the independent team is gone now, but I think there is a use for it.

Instead of having PMC, TNP, on civilian team, have them on independent,
On the independent team, add dedicated slots for:
TNP
PMC
- NEWS
## \- Paramedics

I'm not saying add the territory back or anything, but just use the independent team so it's not confusing to find TNP & PMC. Just have PMC, TNP listed under independent but keep everything else the same. Also add dedicated slots for News & Paramedics under independents.

**Comment by LexTheGreat** [comment]
Really not going to work on anything big that would change the system again. Moving onto Arma 3 after the bug fixes are done.
