### ISSUE TITLE
No Resource Vendor in South Takistan

### ISSUE THREAD

**Issue by gioporta** [LexTheGreat/TLX.Takistan#35]
There used to be a resource vendor by Gas Station 3 in South Takistan, it is no longer there. Now there are two Resource Vendors in Rasman (according to the map), which makes no sense.

**Comment by LexTheGreat** [comment]
He was moved up there so that I could move him around when the time comes. We need to find a good placement because all the resources are now in the south and the selling points are in the north

**Comment by LexTheGreat** [comment]
Todo move over to where jack hammers are sold in the south
