### ISSUE TITLE
Opfor gets set wanted for killing civ terrorists

### ISSUE THREAD

**Issue by gioporta** [LexTheGreat/TLX.Takistan#36]
Not sure about Blufor or TNP, but as Opfor we are set wanted for an "aggravated crime" for killing civilian terrorists. The only time we are not is when they are set wanted by the game and have a bounty. If we set them wanted, it still does it, as the game doesn't recognize our warrants as valid.

**Comment by LexTheGreat** [comment]
https://github.com/LexTheGreat/TLX.Takistan/commit/597cdf9666fb4f6b45f9749a671ffefd59e195df
