### ISSUE TITLE
Restraining Broken for TNP

### ISSUE THREAD

**Issue by ToneAbet** [LexTheGreat/TLX.Takistan#40]
Restraining a civilian results in "You managed to break out of your restraints!" (or something similar) and they break free instantly. The only way to arrest someone is to have two people there, both having the menus open. One person has to restrain while the other clicks arrest at the exact same time.

**Comment by LexTheGreat** [comment]
The restrain check is looking to see if blufor is near, otherwise let the person go. Easy fix

**Comment by LexTheGreat** [comment]
https://github.com/LexTheGreat/TLX.Takistan/commit/be59f4cf35badb3580a092496e5dcd5fffef689c

**Comment by gioporta** [comment]
Bug still exists, fix didn't work.
