### ISSUE TITLE
War timer resets when one faction starts capturing

### ISSUE THREAD

**Issue by gioporta** [LexTheGreat/TLX.Takistan#42]
If one of the factions has already captured all the points, and the 2 minute timer to victory starts and the opposite faction _starts_ capturing one of the points, it resets the timer back to 2 minutes. They don't even need to be successful. This makes it hard to win the war unless we can kill people before they get to the capture flag.

**Comment by LexTheGreat** [comment]
Question, is this blufor's flag you are talking about? They only have one at this time.. If you capture one of opfors does this still occur?

**Comment by gioporta** [comment]
It's happened with both flags as far as I know. It's something that's existed for a long time, it was reported a few months ago because the timer had reset 3 times consecutively in one war. More testing is needed.
