### ISSUE TITLE
HMMWV CROWS can have speed upgrade, but not HMMWV GPK

### ISSUE THREAD

**Issue by gioporta** [LexTheGreat/TLX.Takistan#44]
The GPK is the cheaper version of the CROWS by 100k, with the only difference being the turret, but for some reason you are not able to apply a speed upgrade to it.

**Comment by Solvee98** [comment]
Agreed, to my knowledge the CROWS has more armour than the GPK yet the GPK hasn't got the availability of such upgrades.

**Comment by LexTheGreat** [comment]
https://github.com/LexTheGreat/TLX.Takistan/commit/0600018c4207eecf2271e563f4ff23f0cc754b1e
