### ISSUE TITLE
Mobile phone text messages do not work

### ISSUE THREAD

**Issue by gioporta** [LexTheGreat/TLX.Takistan#45]
If you try to text someone, it always says "X does not have a mobile phone, your text message bounced." The recipient does not receive the texts.

**Comment by LexTheGreat** [comment]
[interaction.sqf#L759](https://github.com/LexTheGreat/TLX.Takistan/blob/f360b8bc9389e80a7c331bb72e3126e76ceedc2b/Awesome/Functions/interaction.sqf#L759)

player_get_bool must be failing on "mobile"

**Comment by LexTheGreat** [comment]
- [ ] Find a better way to check if player has mobile phone, or just remove the check because everyone has one...

**Comment by LexTheGreat** [comment]
https://github.com/LexTheGreat/TLX.Takistan/commit/c8992e8b114b3a1188a73493acef8db2dea332f6

For now
