### ISSUE TITLE
Civ/TNP can use the NATO Air Shop

### ISSUE THREAD

**Issue by gioporta** [LexTheGreat/TLX.Takistan#46]
As a civilian, I can walk into a TNP base and buy the Air Support Officer Training license, and then go to the NATO Air Shop and buy NATO aircraft. Same thing goes for TNP.

The license could be removed from the TNP station since it does not seem to serve any other purpose (although if TNP is getting helis, then something else will have to be done). I can see it causing mass chaos in the future if civilians find out about this loophole and get their hands on armed jets.

**Comment by LexTheGreat** [comment]
https://github.com/LexTheGreat/TLX.Takistan/commit/a02b3c689b4edbcca08dbc149e111603ba8a3aed
