### ISSUE TITLE
MOTD/welcome message outdated

### ISSUE THREAD

**Issue by gioporta** [LexTheGreat/TLX.Takistan#47]
Still mentions Independents must get on Teamspeak, however they no longer exist. Perhaps replace with TNP?

[motd.sqf](https://github.com/LexTheGreat/TLX.Takistan/blob/f360b8bc9389e80a7c331bb72e3126e76ceedc2b/motd.sqf)

Same thing for the welcome message. Says independents can kill Opfor and Blufor on sight. Change to say "Terrorists can kill Opfor, Blufor, and TNP on sight" (_STRS_anfang_03_)

[stringtable.csv](https://github.com/LexTheGreat/TLX.Takistan/blob/f360b8bc9389e80a7c331bb72e3126e76ceedc2b/stringtable.csv)

**Comment by LexTheGreat** [comment]
Hey Giovanni, if you would like to edit the small things like this your self you can, just click the pencil button near "Raw, Blame, History" and edit the changes and there should be a spot near the bottom to put in information and submit a pull request.

https://github.com/LexTheGreat/TLX.Takistan/commit/750157c05a99619c658c1e7907057c892a1a1b45
https://github.com/LexTheGreat/TLX.Takistan/commit/5eed7a9838a1091bda2b7cbb2347ba8f0487bf50

**Comment by LexTheGreat** [comment]
PS: Stringtable.csv isn't used much in the code. Might be a good idea to migrate to that and stop hard coding it..
