### ISSUE TITLE
PMC Stat Reset?

### ISSUE THREAD

**Issue by Solvee98** [LexTheGreat/TLX.Takistan#50]
<Make sure all the checks are checked before submitting, [x] is a checked box!>
- [x] Checked if an issue was already submited like this. (Look into closed Issues as well)
- [x] Have information about the issue.

---
### Expected Outcome (What should occur)

Resume progress made on reconnect
### Actual Outcome (What has occured)

Stats are reset each time logged on
### Steps to Reproduce (How can I reproduce this?) (Only needed for bugs)

Not sure about reproduction of the bug. But everytime I jump on PMC regardless of whether I lose connection, log off or my game crashes while I'm playing. Everytime I get on PMC class my stats are reset. (No licenses and money back to default)

**Comment by LexTheGreat** [comment]
d645a818080ea71ae88a01f8ec19b8c942020ae9
736047ec8d0b6946672d312e19a6e5f705577cfe
