### ISSUE TITLE
War Crime System

### ISSUE THREAD

**Issue by Solvee98** [LexTheGreat/TLX.Takistan#54]
The war crime system as we know is a pain and needs removing. As stated in my previous thread on: http://tlx-gaming.enjin.com/forums/page/2/m/26160904/viewthread/25231010-change-to-opfor-territory-rules

I posted:Might as well throw this into the thread while it's somewhat related. War Crimes are an understandable system but either needs serious fixing or removal. I shouldn't have to be put into situations like this HERE then get IMMMEDIATELY sent to prison for executing a BLUFOR who crossed onto the OPFOR side of the border. 

In which Lex replied: Planning to change it. It was created to fix the problem of opfor and blufor killing each other during peace for no reason.. Pretty sure dnice did something a while back to fix this while near the checkpoints but it seems to not be working...

More likely fix the system than to remove it. 

However this change was never made.

**Comment by gioporta** [comment]
Just want to add in, I did post about this 3 weeks ago [here](http://tlx-gaming.enjin.com/forums/m/26160904/viewthread/26368781-remove-automatic-blacklistingimprisonment-blufor-opfor/post/115099439#p115099439) and Unknown stated that it would be gone in the update.

**Comment by LexTheGreat** [comment]
https://github.com/LexTheGreat/TLX.Takistan/commit/7944c501d1e5034a38b55ae5a12896dbf068ca9c
