### ISSUE TITLE
Sent to jail for not having supporter license when in fact VIP.

### ISSUE THREAD

**Issue by MartinKjenna** [LexTheGreat/TLX.Takistan#55]
<Make sure all the checks are checked before submitting, [x] is a checked box!>
- [x] Checked if an issue was already submited like this. (Look into closed Issues as well)
- [x] Have information about the issue.

---
### Expected Outcome (What should occur)

Not being sent to jail when picking up a supporter weapon when I have the appropriate licenses.
### Actual Outcome (What has occured)

Piked up my stinger > Got sent to jail for 5 min > Checks my licenses > All licenses are there. 
Screenshots: 
https://www.dropbox.com/s/w7k26842rvonl2l/20160322134313_1.jpg?dl=0
https://www.dropbox.com/s/nxpkqhtx9h23r6l/20160322134330_1.jpg?dl=0
### Steps to Reproduce (How can I reproduce this?) (Only needed for bugs)

Pick up a supporter weapon (Perhaps only the stinger is bugged) and fire it.

**Comment by MartinKjenna** [comment]
This also happened as opfor when I pulled out my KSVK. I have both the supporter license and VIP license.

**Comment by LexTheGreat** [comment]
Was fixed

**Comment by LexTheGreat** [comment]
https://github.com/LexTheGreat/TLX.Takistan/commit/5d3e91488c3cc61e12fc01c0a4763a8fec49e6fe

Public'd the fix
